"""
Woolley & Peters ordering-phrase list for presidential directives.

Source: Appendix II of Woolley & Peters, "Presidential Policy Directives and Executive Orders"
(Political Science Quarterly). Phrases were provided by the authors as a Word document and
are reproduced here in cleaned, deduplicated, lower-case form.

ORDERING_PHRASES  — the full cleaned list (~305 phrases), sorted longest-first.
CURATED_OUT       — small set of phrases removed from matching because they fire in clearly
                    non-directive contexts (noun uses, cross-references).  Edit this set to
                    tune precision; the full list is always available in ORDERING_PHRASES.
"""

# ---------------------------------------------------------------------------
# Full cleaned list — 308 phrases extracted from the appendix docx,
# brackets stripped, leading ", " stripped, lower-cased, deduped.
# ---------------------------------------------------------------------------
ORDERING_PHRASES: list[str] = [
    "i would like you to make a thorough and critical review",
    "i have concluded that immediate action must be taken",
    "please report to the office of management and budget",
    "president of the united states of america, designate",
    "contact the other agencies to reach a decision",
    "i am therefore reassuming full responsibility",
    "should immediately give the necessary notice",
    "i am signing this notice of the continuance",
    "it shall be the policy of the united states",
    "shall be the same or substantially the same",
    "i request that each agency head designate",
    "cooperate to the fullest extent possible",
    "i am signing this notice of continuation",
    "is approved for immediate implementation",
    "undertake the following responsibilities",
    "i am now setting a government-wide goal",
    "will you take whatever action is needed",
    "i am herewith directing implementation",
    "i request the head of each department",
    "i want immediate and specific action",
    "please provide to me your assessment",
    "there are no exceptions to this rule",
    "i urge you to carry out these plans",
    "take the following specific actions",
    "i am again setting a general goal",
    "prescribe the following procedure",
    "to provide direction and guidance",
    "hereby, designated and empowered",
    "i ask that you once again review",
    "i therefore expect you to review",
    "will you please send me a report",
    "each of you is being designated",
    "i concur in your recommendation",
    "identifying specific priorities",
    "immediate actions must be taken",
    "you are authorized and directed",
    "you are delegated the authority",
    "you shall be my executive agent",
    "you should respectfully decline",
    "do by this proclamation revoke",
    "i am therefore today directing",
    "i therefore declare and direct",
    "i want every reasonable effort",
    "shall make a continuing effort",
    "this memorandum assigns to you",
    "you will be my executive agent",
    "following specific guidelines",
    "i would like you to institute",
    "shall develop a specific plan",
    "the working group will review",
    "you are authorized to consult",
    "i accept your recommendation",
    "i am appointing a task force",
    "i ask that each of you issue",
    "i should now like to receive",
    "you will take the leadership",
    "designate those individuals",
    "hereby temporarily withdraw",
    "i am setting a general goal",
    "i am, therefore, requesting",
    "i have decided to establish",
    "shall immediately undertake",
    "this memorandum establishes",
    "your general goal should be",
    "hereby officially announce",
    "i am, therefore, directing",
    "i ask that you discontinue",
    "my decision to appoint you",
    "he will then report to me",
    "please issue instructions",
    "this memorandum instructs",
    "hereby further authorize",
    "hereby further designate",
    "i accordingly direct you",
    "i am therefore directing",
    "i ask that you encourage",
    "please submit in writing",
    "shall continue to ensure",
    "take the following steps",
    "you are hereby appointed",
    "agencies should protect",
    "authorized and directed",
    "hereby further delegate",
    "hereby further proclaim",
    "i am today establishing",
    "i am, therefore, urging",
    "shall immediately adopt",
    "this memorandum directs",
    "to withhold my approval",
    "are therefore directed",
    "hereby further declare",
    "hereby further ordered",
    "i am further directing",
    "i am today instructing",
    "i want you to nominate",
    "intention to designate",
    "is accordingly amended",
    "it is my decision that",
    "requested to designate",
    "these guidelines apply",
    "hereby further define",
    "hereby further direct",
    "hereby further exempt",
    "hereby further extend",
    "i ask that you review",
    "i ask you to continue",
    "i urge you to examine",
    "shall submit a report",
    "hereby further amend",
    "i am today directing",
    "i, therefore, direct",
    "shall be implemented",
    "should be considered",
    "you should undertake",
    "continue to develop",
    "hereby discontinued",
    "i also request that",
    "i am also directing",
    "i am directing that",
    "i am reestablishing",
    "i ask that you name",
    "i ask you to ensure",
    "i ask you to search",
    "i further determine",
    "i therefore call on",
    "i urge the agencies",
    "is authorized by me",
    "it is directed that",
    "therefore determine",
    "will be transferred",
    "you are to consider",
    "you recommend to me",
    "you should continue",
    "do further declare",
    "hereby commemorate",
    "hereby give notice",
    "i am also ordering",
    "i am directing you",
    "i am now directing",
    "i am so continuing",
    "i therefore direct",
    "i today direct you",
    "i want you to give",
    "it is my wish that",
    "you are instructed",
    "you must make sure",
    "you should develop",
    "examine in detail",
    "hereby discounted",
    "hereby promulgate",
    "i have determined",
    "please provide me",
    "shall not be used",
    "submit them to me",
    "work closely with",
    "you shall conduct",
    "hereby authorize",
    "hereby designate",
    "hereby determine",
    "hereby encourage",
    "hereby establish",
    "hereby prescribe",
    "hereby recognize",
    "hereby set apart",
    "hereby set aside",
    "hereby supersede",
    "hereby terminate",
    "hereby, modified",
    "i also designate",
    "i am designating",
    "i am setting out",
    "is further amend",
    "please designate",
    "shall be subject",
    "shall coordinate",
    "should encourage",
    "you are directed",
    "hereby allocate",
    "hereby continue",
    "hereby dedicate",
    "hereby delegate",
    "hereby proclaim",
    "hereby prohibit",
    "hereby redefine",
    "hereby transfer",
    "hereby withdraw",
    "i am appointing",
    "i am continuing",
    "i am requesting",
    "provide me with",
    "shall carry out",
    "shall cooperate",
    "should identify",
    "be carried out",
    "develop a plan",
    "form a working",
    "hereby abolish",
    "hereby appoint",
    "hereby approve",
    "hereby certify",
    "hereby commend",
    "hereby commute",
    "hereby declare",
    "hereby empower",
    "hereby exclude",
    "hereby request",
    "hereby require",
    "hereby rescind",
    "hereby reserve",
    "hereby restore",
    "hereby suspend",
    "i am directing",
    "i am extending",
    "i ask that you",
    "i certify that",
    "i have decided",
    "i shall expect",
    "please suggest",
    "should prepare",
    "this directive",
    "do hereby ask",
    "hereby assign",
    "hereby attach",
    "hereby change",
    "hereby create",
    "hereby define",
    "hereby direct",
    "hereby enjoin",
    "hereby exempt",
    "hereby extend",
    "hereby invite",
    "hereby revise",
    "hereby revoke",
    "hereby specif",
    "hereby vested",
    "i also direct",
    "i am charging",
    "i am imposing",
    "i am ordering",
    "i now request",
    "i want you to",
    "is authorized",
    "it is ordered",
    "no agency may",
    "please direct",
    "shall analyze",
    "shall conduct",
    "shall consult",
    "shall convene",
    "shall provide",
    "do authorize",
    "do call upon",
    "do designate",
    "do set aside",
    "hereby amend",
    "hereby grant",
    "hereby modif",
    "hereby order",
    "hereby place",
    "hereby waive",
    "instruct you",
    "shall assess",
    "shall ensure",
    "shall report",
    "shall review",
    "shall submit",
    "designation",
    "do proclaim",
    "hereby call",
    "hereby find",
    "hereby make",
    "hereby urge",
    "i am asking",
    "i am hereby",
    "i authorize",
    "i call upon",
    "i designate",
    "i determine",
    "is assigned",
    "please send",
    "please tell",
    "will assign",
    "designated",
    "do appoint",
    "do approve",
    "do command",
    "do declare",
    "i delegate",
    "i proclaim",
    "is amended",
    "shall plan",
    "call upon",
    "do assign",
    "do direct",
    "do hereby",
    "do invite",
    "i appoint",
    "i approve",
    "i request",
    "you will:",
    "do amend",
    "do order",
    "i desire",
    "i direct",
    "i expect",
    "i hereby",
    "do find",
    "i find",
]

# ---------------------------------------------------------------------------
# Over-generic phrases removed from matching.
# These fire heavily in non-directive contexts (noun uses, cross-references).
# Edit this set to tune precision without losing the phrase from ORDERING_PHRASES.
# ---------------------------------------------------------------------------
CURATED_OUT: set[str] = {
    "this directive",   # fires as "pursuant to this directive", "of this directive"
    "designated",       # noun/adjective use, not a directive action
    "designation",      # noun use
}
